# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches:
      - "**"
    paths:
      - src/**
      - package.json
      - tsconfig.*
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: "1.6"
          ports: "1883:1883 8883:8883"
          config: ${{ github.workspace }}/.devcontainer/mqtt-config/mosquitto.conf
          container-name: mqtt
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn ci:test
        env:
          MQTT_URI: mqtt://localhost:1883

      - name: Create a new tag
        run: yarn ci:tag
        env:
          GITHUBTOKEN: ${{ secrets.GIT_TOKEN }}
          LASTCOMMITSHA: ${{ github.SHA }}
